#ifndef ENUM_H
#define ENUM_H

enum typeAction{AJOUTER, SOUSTRAIRE};
enum TypeRelic{ALTERE, ANANAS, JUS_CITRON, VIN_ROUGE, ARME_EMPOISONNEE};
enum TypeBoss{COCATRIX, DAME_BLANCHE, GRIFFON_ROYAL, 
KATAKAN, WYVERN_ROYAL, FOENARD, LOUP_GAROU, COMPTEUR_BOSS};
enum TypeMonster{NEKKER, ARAKAS, LOUP, CHIEN, NOYEUR, HARPIE,
OURS, SIRENE, COMPTEUR_MONSTRE};






#endif