#ifndef ENUM_H
#define ENUM_H

enum ActionType{ADDITION, SOUSTRACT};
enum RelicType{ALTERE, ANANAS, JUS_CITRON, VIN_ROUGE, ARME_EMPOISONNEE,
    COMPTEUR_RELIQUE};
enum BossType{COCATRIX, DAME_BLANCHE, GRIFFON_ROYAL,
    KATAKAN, WYVERN_ROYAL, FOENARD, LOUP_GAROU, COMPTEUR_BOSS};
enum MonsterType{NEKKER, ARAKAS, LOUP, CHIEN, NOYEUR, HARPIE,
    OURS, SIRENE};




#endif